### ISSUE TITLE
How to write tests to know Stream.io is receiving the activity data?

### ISSUE THREAD

**Issue by gianpaj** [GetStream/Stream-Example-Nodejs#16]
I have an app similar to Instagram and I have JS tests which trigger API calls for example to follow a user.

Is there a way to find out if the follow activity went through to Stream.io programmatically?

Thanks

**Comment by dwightgunning** [comment]
Preferrably for unit tests you'd mock the external service so your test suite runs faster and you won't use your quotas unnecessarily.

The Feed.follow() function returns a Promise so you can provide a rejection handler method.

Closing for now but happy to continue the discussion.

Reminder: general implementation questions are best directed to Stack Overflow with the [getstream-io](https://stackoverflow.com/questions/tagged/getstream-io) tag in order to benefit the Stream developer community.
