### ISSUE TITLE
Error: Missing token

### ISSUE THREAD

**Issue by collegeminer** [GetStream/Stream-Example-Nodejs#7]
Is this an error or am I missing something here when I run your same app.

Error: Missing token, in client side mode please provide a feed secret

![image](https://cloud.githubusercontent.com/assets/2465014/15871147/112c4494-2cc1-11e6-9773-d34cc352a0ea.png)

**Comment by collegeminer** [comment]
I think this was because I didn't place my appid and secret in getstream.js. However, now once I try to login then it just hangs.

**Comment by matthisk** [comment]
Yes not providing an api key and secret in getstream.js will result in this error. What do you mean by "it just hangs" can you provide a bit more context?

**Comment by collegeminer** [comment]
It just continues to try to load, but never loads the page

**Comment by tschellenbach** [comment]
Hi @matthisk this could be related to the renaming of the feed groups. IE flat-> timeline, aggregated -> timeline_aggregated.

**Comment by collegeminer** [comment]
What do I need to do?

**Comment by matthisk** [comment]
@tschellenbach ah yes that would break the application, I am currently updating the default feed groups to match the configuration you get once you signup for a Stream account. However @collegeminer it seems that in this case there is also something else going wrong since you are experiencing issues with signing in, did you configure your GITHUB_CLIENT_SECRET and GITHUB_CLIENT_ID? Can you try without github sign in?

**Comment by collegeminer** [comment]
I updated the ClientID and Secret in config/config.js. Is this the only place that it needs to be changed?

**Comment by matthisk** [comment]
Yes that is the only spot. Also try to pull in the new changes from master (or download the entire repo if you got a zip before). I made some changes to the repo to fix the issue mentioned by @tschellenbach.
